<div scroll="auto" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="row">
 

<center>
<h3 class="title"> Perfil de la Empresa </h3>
<a id="header_logo" href="http://www.sosmedica.com/" title="SOSMEDICA.COM"> <img class="logo" alt="Responsive image" src="<?php echo BASE_URL; ?>public/img/logoweb.png" alt="SOSMEDICA.COM"> </a>
</center>

<div class="col-md-9">
<div class="row">

<div class="sub-title"> <b> Breve historia de la empresa: </b> </div>
<div class="texto"> 
<b> <span class="sosmedica">S.O.S MEDICA C.A.</span> Ofrece a sus clientes un servicio integral en
proyectos, brindando asesoría, y contando con
profesionales en los campos de las finanzas y la
administración, por lo que podemos gerencial
la dotación, mantenimiento, equipamiento y
cubrir otras necesidades de hospitales, clínicas,
laboratorios de investigación, médicos
privados, instituciones de docencia, empresas
petroleras, etc. </b>
</div>


<div class="sub-title"> <b> Nuestros servicios son:  </b> </div>
	<div class="texto"><b> <ul>
		<li>Importación de equipos e insumos.</li>
		<li>Servicio de mantenimiento técnico.</li>
		<li>Estudios de factibilidad.</li>
		<li>Asesoramiento e investicación de proyectos.</li>
		<li>Planificación y desarrollo de proyectos.</li>
		<li>Adiestramiento y puesta en marcha.</li>
	</ul>  </b>
    </div>
  <div class="col-md-6 texto"> 
			<b><span class="sosmedica">S.O.S MEDICA C.A.</span> se enfoca hacia la distribución de tecnología para la salud.
			Hemos logrado posicionarnos cómo un confiable suplidor de diversos organismos
			como: Hospitales, Alcaldías, Ambulatorios, así
			como también ante empresas del sector médico privado.
			Nuestros productos cumplen con las más estrictas certificaciones y normas nacionales e
			internacionales, lo que garantiza su altísima calidad.
			Nuestra Cooperativa cuenta con un personal
			administrativo capacitado y con la Experiencia
			necesaria para así poder atender todas las
			necesidades requeridas por nuestros clientes.</b>
  </div> 
  <div class="col-md-3"> <img class="img-rounded" src="<?php echo BASE_URL; ?>public/img/quienessomos1.png"></div>

<div class="col-md-12 sub-title"> <b> Nuestra Misión:</b> </div>
<div class="col-md-12 texto"> 
<b>El propósito fundamental de <span class="sosmedica">S.O.S MEDICA C.A.</span> es proveer productos y servicios para la
salud de tal calidad que nuestros clientes reciban un valor superior, nuestros empleados y
socios comerciales compartan nuestro éxito y nuestro nombre sea inequivocablemente
asociado con calidad, confianza y superior servicio al cliente. </b>
</div>
<div class="col-md-12 sub-title"> <b> Nuestra Visión:</b> </div>
<div class="col-md-12 texto">
<b>Nuestra Visión es de llegar a ser reconocidos el ámbito nacional e internacional por nuestros
clientes como el suplidor más confiable de Equipos médicos. </b>
</div>
<div class="col-md-12 sub-title"> <b> Actualmente:</b> </div>
<div class="col-md-12 texto fin">
	<b> En la actualidad la empresa se dedica a la distribución y comercialización de tecnología para
la salud en la Republica Bolivariana de Venezuela manejamos líneas exclusivas en áreas
como: Cardiología, cirugía, ciudadanos hospitalarios, diagnostico, imaginología,
microscopia, neonatología, odontología, oftalmología, optometría, etc. </br> </br>
<span class="sosmedica">S.O.S MEDICA C.A.</span> Se encarga de brindar el soporte técnico a nuestros clientes. Contamos
con una compañías destinada al mantenimiento y reparación de equipos, con personal
especializado y entrenado en cada una de las sedes de nuestros proveedores y con un gran
inventario de repuestos originales; ofreciendo así una garantía no sólo del producto en sí,
sino de un servicio y respaldo total a cada uno de los equipos y sistemas vendidos por <span class="sosmedica">S.O.S
MEDICA C.A.</span> y inconsecuencia a la vanguardia de más recientes desarrollos de la industria.
Para brindar un mejor y más rápido servicio a nuestros clientes y atender rápidamente la
demanda de los mercados, contamos con nuestras propias oficinas en Venezuela. </b>
</div>

</div>
</div>





</div>

</div>