
 
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6  col-sm-offset-3 col-md-offset-3 col-lg-offset-3">
<div class="header-titulos">Cambio de contraseña</div>






 <div class="col-xs-10 col-sm-12 col-md-12 col-lg-12 ">


           <div class="form-group ">
              <label class="control-label">Ingrese su clave actual</label>
              
                <input type="password" type="text" class="form-control" id="actual" name="actual" required="required">
              
          </div>
          <div class="form-group">
              <label class=" control-label">Ingrese su nueva clave</label>
            
                <input type="password" type="text" class="form-control" id="nueva" name="nueva" required="required">
              
          </div>
          <div class="form-group ">
              <label class=" control-label">Confirmar su nueva clave</label>
          
                <input type="password" type="text" class="form-control" id="confirmar" name="confirmar" required="required">
              
          </div>
            <div class="form-group ">
              <button id="cambiarclave" type="button" class="btn btn-primary btn-sm">Cambiar Clave</button>
            <button onclick="javascript:history.back()" class="btn btn-primary btn-sm">Cancelar</button>

          </div>
    
</div>


</div>