
   <div class="col-xs-10 col-sm-8 col-md-8 col-lg-8  col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">

   <div class="header-titulos">REGISTRO DE PROFESOR</div>

<form id="form_registro">
  
<div class="form-group ">
      <label class="">Cedula</label>
      <input type="text" class="form-control" name="cedula" id="cedula" placeholder="Cedula" >
    

   
  
<div class="form-group">
 <center>
      <button id="registrar" type="button" class="btn btn-primary">REGISTRAR</button>
      <a href="<?php echo BASE_URL;?>"> REGRESAR </a>
 </center>
  </div>

</form>
</div>












  




