<div class="col-xs-10 col-sm-8 col-md-8 col-lg-8  col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">

    <div class="header-titulos">VENTAS</div>


	<div id="alumprofe" class="row">
		<div id="" class="col-xs-12 col-md-10 col-md-offset-1 ">
		
		<form id="form_registro">
  
<div class="form-group ">
      <label class="">Cedula</label>
      <input type="nombres" class="form-control" name="cedula" id="cedula" placeholder="Cedula" >
       <input type="hidden" id="vn" value="0"  >
     
  
  <div class="form-group">
    <label class="">Nombres</label>
    <input type="text" class="form-control" name="nombres" id="nombres" placeholder="Nombres">
  </div>

 
  
  <div class="form-group">
    <label class="">Coordinacion</label>
      <input type="text" class="form-control" name="coord" id="coord" placeholder="Coordinacion">
  </div>

  <div class="form-group">
    <label class="">Productos</label>
   <textarea class="form-control" name="producto" id="producto"></textarea>  
  </div>

<div class="form-group">
    <label class="">Total a pagar</label>
      <input type="number" class="form-control" name="total" id="total" placeholder="total">
  </div>

  <div class="form-group">
    <label class="">Abono</label>
      <input type="number" class="form-control" name="abono" id="abono" placeholder="abono">
  </div>

</div>

   
  
<div class="form-group">
 <center>
      <button id="registrar_venta" type="button" class="btn btn-primary">REGISTRAR</button>
      <a class="btn btn-primary" href="<?php echo BASE_URL;?>"> REGRESAR </a>
 </center>
  </div>

</form>
		
	</div>


</div>

<div class="fixer">
  
<center><b>Datos de compras</b></center><br>

</div>