<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">

<div class="row">

<div class="col-md-6 col-md-offset-3" id="tituloo">Agregar Almacen</div>

<div class="col-md-6 col-md-offset-3"> 

<form id="form_agregar_equipo" method="post" action=" <?php echo BASE_URL ?>administrar/guardar_almacen" >
  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre Producto">
  </div>
  


  <div class="form-group">
    <label for="presentacion">direccion</label>
    <textarea  class="form-control" id="direccion" name="direccion" placeholder="direccion"></textarea>
  </div>

  <div class="form-group">
    <label for="presentacion">telefono</label>
    <input type="text" class="form-control" id="telefono" name="telefono" placeholder="xxxx-xxx-xx-xx">
  </div>

  <div class="form-group ">
    <label class=" control-label">Horarios</label>
    <input  type="text" class="form-control" multiple="multiple" id="horario" name="horario">
  </div>


<div>  
                                        <center> 
                                                <button type="button" onclick="javascript:history.back(1)" class="btn btn-default">Atras</button>
                                                <button type="submit" class="btn btn-default">Guardar</button>
                                        </center>
                                </div>
                                 <div id="redireccion">  
                                        <center> 
                                                <a href="<?php echo BASE_URL ?>administrar/ges_almacen" >ir a administrar almacen</a>
                                        </center>
                                </div>
</form>
	
</div>

</div>


</div>