<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">

<div class="row">

<div class="col-md-6 col-md-offset-3" id="tituloo">Administrar Categorias y Marcas</div>

<div class="col-md-6 col-md-offset-3"> 

<div class="form-group">
<div class="row">
  

<div class="col-md-12"> <label for="nombre"> Categorias</label> </div>

<div class="col-md-10">
  
 <select class="form-control" name="categoria" id="categoria">
 <option value="">--> Seleccione <--</option>

    <?php for($i = 0; $i < count($this->cama['categorias']); $i++): ?>
                           
    <option value="<?php  echo $this->cama['categorias'][$i]['id_categoria']; ?>"><?php  echo $this->cama['categorias'][$i]['categoria'];?></option>
                     

     <?php endfor; ?>

</select>
</div>
<div class="col-md-1 btn btn-default" id="agregar_categoria"><span class="glyphicon glyphicon-plus"></span></div>
<div class="col-md-1 btn btn-default btn_eliminar" id="eliminar_categoria"><span class="glyphicon glyphicon-minus"></span></div>
</div>
  </div>




<div class="form-group">
<div class="row">
  

<div class="col-md-12"> <label for="nombre">Marcas de productos</label> </div>

<div class="col-md-10">
  


 <select class="form-control" name="marca" id="marca_producto">
 <option value="">--> Seleccione <--</option>

    <?php for($i = 0; $i < count($this->cama1['marcas']); $i++): ?>
                           
    <option value="<?php  echo $this->cama1['marcas'][$i]['id_marca']; ?>"><?php  echo $this->cama1['marcas'][$i]['marca'];?></option>
                     

     <?php endfor; ?>

</select>
</div>
<div class="col-md-1 btn btn-default btn_add" id="agregar_marca_producto"><span class="glyphicon glyphicon-plus"></span></div>
<div class="col-md-1 btn btn-default btn_eliminar" id="eliminar_marca_producto"><span class="glyphicon glyphicon-minus"></span></div>
</div>
  </div>

  <div class="form-group">
<div class="row">
  

<div class="col-md-12"> <label for="nombre">Marcas de equipos</label> </div>

<div class="col-md-10">
  


 <select class="form-control" name="marca" id="marca_equipo">
 <option value="">--> Seleccione <--</option>

    <?php for($i = 0; $i < count($this->cama2['marcas']); $i++): ?>
                           
    <option value="<?php  echo $this->cama2['marcas'][$i]['id_marca']; ?>"><?php  echo $this->cama2['marcas'][$i]['marca'];?></option>
                     

     <?php endfor; ?>

</select>
</div>
<div class="col-md-1 btn btn-default btn_add" id="agregar_marca_equipo"><span class="glyphicon glyphicon-plus"></span></div>
<div class="col-md-1 btn btn-default btn_eliminar" id="eliminar_marca_equipo"><span class="glyphicon glyphicon-minus"></span></div>
</div>
  </div>

                                <div>  
                                        <center> 
                                                <button type="button" onclick="javascript:history.back(1)" class="btn btn-default">Atras</button>
                                                <button type="submit" class="btn btn-default">Guardar</button>
                                        </center>
                                </div>
                                 <div id="redireccion">  
                                        <center> 
                                                <a href="<?php echo BASE_URL ?>administrar" >ir a administrar</a>
                                        </center>
                                </div>



 </div>


 
  </div>
 </div>

  
	