<div scroll="auto" class="col-xs-12">

<div class="row"> 

<div class="col-md-10 col-md-offset-1" id="tituloo">Administra tus Almacenes</div>

<div class="col-md-10 col-md-offset-1"> 


<div class="row">
   
<div class="area_de_busqueda row"> 

<div>

</div> 
<div id="resultados">
  

	<table class="table table-striped">
		<thead>
			<th>Nombre</th><th>Direccion</th><th>Telefono</th><th>Horario</th><th>Acciones</th>

		</thead>
		<tbody id="cuerpotabla">
			<tr>
				<td colspan="5">
					<center><h3>Cargando Almacenes...</h3> </center>
				</td>
				
			</tr>

		</tbody>
	</table>



</div> 


</div>




</div>


	
</div>

</div>


</div>