<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">

<div class="row">

<div class="col-md-6 col-md-offset-3" id="tituloo">Administra tus Equipos</div>

<div class="col-md-8 col-md-offset-2"> 


<div class="row">
   <div class="input-group">
      <input id="buscar_de_ges_equipo" type="text" class="form-control" placeholder="Buscar...">
      <span class="input-group-btn">
        <button class="btn btn-default btnbuscar" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
      </span>
    </div>

<div class="area_de_busqueda row"> 

<div>
  Cambiar esta mierda Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat reiciendis quod recusandae est officiis cum, cupiditate consequuntur obcaecati excepturi eos molestias, vitae ut hic dolorum! Maiores voluptatum ratione aperiam eligendi.

</div> 
<div id="resultados">
  




</div> 




</div>

 					  <div>  
                                        <center> 
                                                <button type="button" onclick="javascript:history.back(1)" class="btn btn-default">Atras</button>
                                        </center>
                                </div>
                                 <div id="redireccion">  
                                        <center> 
                                                <a href="<?php echo BASE_URL ?>administrar/agregarequipo" >Agregar un equipo</a>
                                        </center>
                                </div>

</div>




</div>


	
</div>

</div>


</div>