<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">

<div class="row">
	
	
<article id='collace_opt'>
			<div id='capas_tras_up' class="uno">
			<div id="fondo_gris">
				<span class="glyphicon glyphicon-tag" aria-hidden="true"> Productos
				</span>
			</div>
			</div>
			<div id='capas_tras_donw'>
				
				<div id="opt_" data-accion="agregar" data-controller="agregar">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="gestionar" data-controller="proveedor">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
				
				


			</div>
</article>

<article id='collace_opt'>
			<div id='capas_tras_up' class="dos">
				<div id="fondo_gris">
				<span class="glyphicon glyphicon-hdd" aria-hidden="true"> Equipos
				</span>
				</div>
			</div>
			<div id='capas_tras_donw' >
				<div id="opt_" data-accion="agregarequipo" data-controller="agregar">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="gestionar" data-controller="banco">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
			</div>
</article>


</div>


</div>