<div scroll="auto" class="col-xs-12">

<div class="row">
	
	
<article id='collace_opt'>
			<div id='capas_tras_up' class="uno">
			<div id="fondo_gris">
				<span class="glyphicon glyphicon-tag" aria-hidden="true"> Productos
				</span>
			</div>
			</div>
			<div id='capas_tras_donw'>
				
				<div id="opt_" data-accion="agregar" data-controller="agregar">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="ges_producto" data-controller="proveedor">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
				
				


			</div>
</article>

<article id='collace_opt'>
			<div id='capas_tras_up' class="dos">
				<div id="fondo_gris">
				<span class="glyphicon glyphicon-hdd" aria-hidden="true"> Equipos
				</span>
				</div>
			</div>
			<div id='capas_tras_donw' >
				<div id="opt_" data-accion="agregarequipo" data-controller="agregar">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="ges_equipo" data-controller="banco">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
			</div>
</article>


<article id='collace_opt'>
			<div id='capas_tras_up' class="tres">
				<div id="fondo_gris">
				<span class="glyphicon glyphicon-home" aria-hidden="true"> Almacenes
				</span>
				</div>
			</div>
			<div id='capas_tras_donw' >
				<div id="opt_" data-accion="add_almacen" data-controller="agregar">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <br/>
					<font>Agregar</font>
				</div>
				<div id="opt_" data-accion="ges_almacen" data-controller="banco">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><br/>
					<font>Gestionar</font>
				</div>
			</div>
</article>
<article id='collace_opt'>
			<div id='capas_tras_up' class="uno">
			<div id="fondo_gris">
				<span class="glyphicon glyphicon-tag" aria-hidden="true"> Marcas || Categorias
				</span>
			</div>
			</div>
			<div id='capas_tras_donw'>
				
				<div id="opt_" class="especial" data-accion="add_mc" data-controller="agregar">
					<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> <br/>
					<font>Gestionar</font>
				</div>
			
				
				


			</div>
</article>


</div>


</div>