<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">

<div class="row">

<div class="col-md-6 col-md-offset-3" id="tituloo">Actualizar Almacen</div>



<div class="col-md-6 col-md-offset-3"> 

<form id="form_update_almacen" method="post" action=" <?php echo BASE_URL ?>administrar/editar_almacen" >
  
  <input type="hidden"  value="<?php echo $this->almacen['id_almacen']?>" id="id_almacen" name="id_almacen">

  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control" value="<?php echo $this->almacen['nombre']?>" id="nombre" name="nombre" placeholder="Nombre Producto">
  </div>
  


  <div class="form-group">
    <label for="presentacion">direccion</label>
    <textarea  class="form-control"  id="direccion" name="direccion" placeholder="direccion"><?php echo $this->almacen['telefono']?>
    </textarea>
  </div>

  <div class="form-group">
    <label for="presentacion">telefono</label>
    <input type="text" class="form-control" value="<?php echo $this->almacen['telefono']?>" id="telefono" name="telefono" placeholder="xxxx-xxx-xx-xx">
  </div>

  <div class="form-group ">
    <label class=" control-label">Horarios</label>
    <input  type="text" class="form-control" value="<?php echo $this->almacen['horario']?>" multiple="multiple" id="horario" name="horario">
  </div>



 <div>  <center> <button type="submit" class="btn btn-default">Guardar</button> </center></div>
  
</form>
	
</div>

</div>


</div>