<div scroll="auto" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="row">
 
<div class="col-md-12 hidden-xs hidden-phone"> 
<div class="row">
   <div id="demo">
        <div class="container">
          <div class="row">
            <div class="span12">
              <div id="owl-demo" class="owl-carousel">

                <div class="item"><img src="layout/layout_sosmedica/img/carrusel3.png" alt="SOS MEDICA"></div>
                <div class="item"><img src="layout/layout_sosmedica/img/carrusel2.png" alt="SOS MEDICA"></div>
                <div class="item"><img src="layout/layout_sosmedica/img/carrusel1.png" alt="SOS MEDICA"></div>
                <div class="item"><img src="layout/layout_sosmedica/img/carrusel3.png" alt="SOS MEDICA"></div>
                <div class="item"><img src="layout/layout_sosmedica/img/carrusel2.png" alt="SOS MEDICA"></div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
</div>

<div class="col-md-4 pad"> <h4 class="ultimos"><b>Chequea nuestros ultimos productos: </b></h4> </div>
<div class="col-md-12">
<div class="row">

<?php 

function getSubString($string, $length=NULL)
{
    //Si no se especifica la longitud por defecto es 50
    if ($length == NULL)
        $length = 50;
    //Primero eliminamos las etiquetas html y luego cortamos el string
    $stringDisplay = substr(strip_tags($string), 0, $length);
    //Si el texto es mayor que la longitud se agrega puntos suspensivos
    if (strlen(strip_tags($string)) > $length)
        $stringDisplay .= ' ...';
    return $stringDisplay;
}


for($i = 0; $i < count($this->productos); $i++): 

if(isset($this->productos)){
  
?>

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
     <a href="<?php  echo BASE_URL."product/view_product/".$this->productos[$i]['producto']['id_producto'];?>" class="titulo-product" title="<?php  echo $this->productos[$i]['producto']['nombre'] ;?>"> <b><?php  echo getSubString($this->productos[$i]['producto']['nombre'], 13) ;?> </b></a>
  </div>
    <a href="<?php  echo BASE_URL."product/view_product/".$this->productos[$i]['producto']['id_producto'];?>" class="thumbnail producto-img">
      <img title="<?php  echo $this->productos[$i]['producto']['nombre'] ;?>" src="<?php  echo BASE_URL."public/img/publicaciones/".$this->productos[$i]['img'][0]['nombre'] ;?>" alt="<?php  echo $this->productos[$i]['producto']['nombre'] ;?>">
      <?php if($i%2==0) {?>
    <div><center> Disponible <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </center></div>

    <?php } else{?>

    <div class="nodisponible"><center> No disponible <span class="glyphicon glyphicon-remove"></span> </center></div> <?php } ?>
    <center><div class="btn btn-default btn-xs detalles"> Detalles <span class="glyphicon glyphicon-list"></span> </div></center>
    </a>
    
  </div>
  <?php } else{ ?>

  <div class="col-md-12 busqueda"> No existen productos cargados en el sistema</div>

                            <?php  } endfor; ?>
  
    
</div>
</div>





</div>

</div>