<div scroll="auto" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="row">

<div class="col-md-12"> 
<div class="row">
   <div id="demo">
        <div class="container">
          <div class="row">
            <div class="span12">
              <div id="owl-demo" class="owl-carousel">

                <div class="item"><img src="layout/layout_sosmedica/img/carrusel3.png" alt="The Last of us"></div>
                <div class="item"><img src="layout/layout_sosmedica/img/carrusel2.png" alt="GTA V"></div>
                <div class="item"><img src="layout/layout_sosmedica/img/carrusel1.png" alt="Mirror Edge"></div>

              </div>
            </div>
          </div>
        </div>
    </div>
</div>
</div>


<div class="col-md-12">
<div class="row">

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
  
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
  
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>

  <div class="col-xs-6 col-sm-3  col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
</div>
</div>





</div>

</div>