<div scroll="auto" class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">

<div class="col-md-8"> 

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="layout/layout_sosmedica/img/carrusel1.png" alt="SOSMEDICA Compañia Anonima - Venta de equipos medicos">
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img src="layout/layout_sosmedica/img/carrusel2.png" alt="SOSMEDICA Compañia Anonima - Venta de equipos medicos">
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img src="layout/layout_sosmedica/img/carrusel3.png" alt="SOSMEDICA Compañia Anonima - Venta de equipos medicos">
      <div class="carousel-caption">
        
      </div>
    </div>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Siguiente</span>
  </a>
</div>

</div>

<div class="col-md-4">
	<h3> Area libre ^^ </h3>
</div>
<div class="col-md-12">

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
  
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>

  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
  
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>

  <div class="col-xs-6 col-sm-3  col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
  
  <div class="col-xs-6 col-sm-3 col-md-2 producto">
  <div class="titulo-producto">
    <center> Producto </center>
  </div>
    <a href="#" class="thumbnail producto-img">
      <img src="public/img/pp.jpg" alt="...">
    </a>
  </div>
</div>







</div>